#!/bin/bash

# config stuff (modify this section of the script to fit your environment)
ghidra_install_dir="/opt/ghidra"
ghidra_root="$(getent passwd ghidra | cut -d':' -f6)"
ghidra_allow_anonymous=false
ghidra_public_ip="$(curl -s eth0.me)"

# boolean goes into $result when this function exits
read_boolean() {
	result="";
	read -rp "$1 " result
	if [[ "$result" == "y" ]] || [[ "$result" == "yes" ]] || [[ "$result" == "true" ]]; then
		result=true
	elif [[ "$result" == "n" ]] ||  [[ "$result" == "no" ]] || [[ "$result" == "false" ]]; then
		result=false
	else
		echo "Invalid verb (yes/no, true/false are expected)."
		read_boolean "$1"
	fi
}

review_config() {
	echo "Configuration (for review):"
	echo "Ghidra Installation Directory: ${ghidra_install_dir}"
	echo "Ghidra Server Root: ${ghidra_root}"
	echo "Public IP Address: ${ghidra_public_ip}"
	echo "Ghidra allowing anonymous access: ${ghidra_allow_anonymous}"

	read_boolean "Is it OK to continue?"
	if ! $result; then
		exit;
	fi
}

configure_file() {
	cat $1 | \
		sed "s|@ghidra_home@|${ghidra_install_dir}|" | \
		sed "s|@ghidra_root@|${ghidra_root}|" | \
		sed "s|@public_ip@|${ghidra_public_ip}|" | \
		sed "s|@anonymous@|${ghidra_anonymous_arg}|" > $2;
}

configure_files() {
	cp -rv files stage

	if $ghidra_allow_anonymous; then
		ghidra_anonymous_arg="-anonymous"
	fi

	# Configure files as needed
	configure_file stage/ghidra.service.in stage/ghidra.service
	configure_file stage/server.conf.in stage/server.conf
}

install_configured_files() {
	# copy files into the right place
	cp stage/ghidra.service /etc/systemd/system/ghidra.service

	# ditto for ghidra server stuff
	cp -r stage/ghidra_systemd_run stage/log4j/ ${ghidra_root}/
	mkdir ${ghidra_root}/repositories

	chown -Rvv ghidra:ghidra ${ghidra_root}/

	# Replace server.conf (but keep a backup just in case we ended up breaking things)
	cp ${ghidra_install_dir}/server/server.conf ${ghidra_install_dir}/server/server.conf.ghidra
	cp stage/server.conf ${ghidra_install_dir}/server/server.conf

	echo "Done. I hope."
	rm -rf stage
}

review_config
configure_files
install_configured_files
